name: Import dataset

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Location of DVC or Git repository to download from'     
        required: true
        default: 'git@github.com:daavoo/dataset-pyday-bcn-2021.git'
      path:
        description: 'Path to a file or directory within the repository'     
        required: true
        default: 'data' 
      rev:
        description: 'Commit hash, branch or tag name, etc. (any Git revision)'     
        required: false
        default: 'solution'

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        run: |
          pip install -r requirements.txt

      - name: DVC import
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          dvc import ${{ github.event.inputs.url }} ${{ github.event.inputs.path }} --rev ${{ github.event.inputs.rev }}

      - name: Push changes
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          dvc push

      - name: CML PR 
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cml pr "${{ github.event.inputs.path }}*" ".gitignore" "**/.gitignore"
